In [ ]:
import numpy as np

lst1 = [11,22,33,44,55,66,77,88,99,110]

arr1 = np.array(lst1)
print(type(arr1))

<class 'numpy.ndarray'>


In [ ]:

tup1 = (12,33,34,43,56,67,87,)
arr2 = np.array(tup1)
print(type(arr2))

<class 'numpy.ndarray'>


In [ ]:
set1= {1,22,345,5,66,7,True,False, 'Python'}
arr3 = np.array(set1)
arr3

array({False, 1, 66, 5, 7, 'Python', 22, 345}, dtype=object)

In [ ]:
dict1 = {'a':[1,2,3,4,5,6], 'b':(True,False), 'c':'python', 'd':'programming'}
arr4= np.array(dict1)
arr4

array({'a': [1, 2, 3, 4, 5, 6], 'b': (True, False), 'c': 'python', 'd': 'programming'},
      dtype=object)

In [ ]:
str1 = 'python programming'
arr5 = np.array(str1)
print(arr5)

python programming


In [ ]:
arr1d = np.array([1,2,3,4,5,6,7,8,9,10])
print(arr1d)
arr1d.ndim

[ 1  2  3  4  5  6  7  8  9 10]


1

In [ ]:
arr2d = np.array([[1,2,3,4,5],[6,7,8,9,10]])

print(arr2d)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [ ]:
arr3d= np.array([[[1,2,3],[2,3,4]],[[3,4,5],[4,5,6]]])
print(arr3d)
arr3d.ndim

[[[1 2 3]
  [2 3 4]]

 [[3 4 5]
  [4 5 6]]]


3

In [ ]:
a = np.array(42)
b = np.array([1,2,3,4,5])
c = np.array([[1,2,3,4,5],[6,7,8,9,10]])
d = np.array([[[1,2,3],[2,3,4]],[[3,4,5],[4,5,6]]])
e = np.array([[[[1,2,3],[2,3,4]],[[3,4,5],[4,5,6]]],
             [[[1,2,3],[2,3,4]],[[3,4,5],[4,5,6]]]])


print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)
print(e.ndim)

0
1
2
3
4
