A collection of modules that are linked together is also known as aPython Library. It has code bundles that can be used again and again in different programs.

In [ ]:
import numpy as np

In [ ]:
#print vector of 0

v = np.zeros(10)
print(v)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [ ]:
print('%d bytes' %(v.size*v.itemsize))

80 bytes


In [ ]:
v = np.zeros(10)
v[4]= 1
print(v)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [ ]:
v= np.arange(10,20)
print(v)

[10 11 12 13 14 15 16 17 18 19]


In [ ]:
v= np.arange(10,50)
print(v)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [ ]:
v= np.arange(10,50)
print(v)
print(type(v))

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
<class 'numpy.ndarray'>


In [ ]:
v= np.arange(10,50)
print(v)
v= v [::-1]
print(v)


[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [ ]:
v = np.arange(9).reshape(3,3)
print(v)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
nz = np.nonzero([1,0,0,2,0,0,3,0,0,0,4,0,0,0,0,0,5,0,0,0,0,0,6])
print(nz)

(array([ 0,  3,  6, 10, 16, 22]),)


In [ ]:
v = np.eye(3)
print(v)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
v = np.eye(3)
print(v)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
v = np.eye(5)
print(v)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [ ]:
v = np.random.random(10)
print(v)

[0.88687745 0.39742515 0.88113674 0.60046398 0.77652814 0.43642219
 0.80937642 0.8116758  0.71878087 0.23720508]


In [ ]:
v = np.random.random((10,10))
print(v)

[[1.13238137e-01 4.35403660e-01 6.74844759e-01 1.57291627e-01
  9.55491305e-01 7.36624711e-01 3.82369538e-02 3.59581458e-01
  5.60489757e-01 9.06607034e-02]
 [7.34593617e-01 6.46581223e-01 1.90630762e-01 5.56240988e-01
  6.05185914e-01 1.41758389e-02 8.51064445e-02 9.78531750e-01
  5.42608657e-01 6.56912374e-01]
 [2.92128020e-01 5.29874497e-01 8.40198877e-01 8.72339115e-01
  9.31555241e-01 2.12147579e-01 8.85911918e-01 7.18315635e-02
  8.82494368e-01 6.96808723e-01]
 [5.65633861e-01 3.75985408e-01 5.83982725e-01 7.04760538e-02
  5.56655057e-01 1.77670294e-01 4.00131080e-01 2.34681384e-01
  1.52481895e-01 1.52821227e-01]
 [4.73785268e-01 1.65585669e-01 9.29552356e-01 3.02209290e-01
  4.67667237e-01 6.10063036e-01 6.05913157e-01 2.34026337e-01
  9.56402150e-01 9.63064469e-01]
 [8.38962358e-01 2.86684466e-01 2.16183174e-01 4.33988108e-01
  8.57370427e-01 6.57176278e-01 1.35581260e-01 8.30917970e-01
  4.68750246e-02 2.30498337e-01]
 [3.76621749e-01 2.83500928e-01 4.51316854e-01 8.39887012e

In [ ]:
v = np.random.random((10,10,10))
print(v)

[[[7.36371431e-01 1.75615346e-01 8.56411220e-01 8.46293191e-01
   8.42988991e-01 6.82246193e-01 2.79474582e-01 6.96628345e-01
   5.36320757e-01 8.66300818e-01]
  [5.34114465e-01 9.46900688e-01 8.42968971e-01 2.70516892e-01
   1.52554806e-01 5.18243002e-01 6.12620051e-01 3.98282334e-02
   4.54897347e-01 3.49706446e-01]
  [8.17598465e-01 4.38635750e-01 1.19035225e-01 1.84406679e-01
   9.46976689e-01 3.42688227e-02 5.06573563e-01 6.08425490e-01
   7.57752134e-01 4.63588887e-03]
  [6.28630998e-01 9.29781802e-01 3.17865413e-01 2.82105008e-01
   2.06271646e-01 3.45324319e-01 2.63250412e-01 2.71032666e-01
   6.04035228e-01 4.42977461e-01]
  [9.51076469e-02 2.06157471e-01 4.48428492e-02 2.49132732e-01
   8.27126497e-01 3.86109304e-01 1.24903229e-01 5.26666548e-01
   2.70151523e-01 2.45212415e-01]
  [9.52511591e-01 7.24754776e-01 3.68339370e-01 1.17918125e-02
   6.63518334e-01 2.14102911e-01 7.18662586e-01 2.55588537e-01
   7.20195960e-01 2.89389979e-01]
  [4.15559445e-01 6.18826467e-02 2.18036

In [ ]:
v = np.random.random((3,3,3))
print(v)

[[[0.88924445 0.68260253 0.49410586]
  [0.74875405 0.87255097 0.51230363]
  [0.45693198 0.12878492 0.51505185]]

 [[0.68099694 0.27619783 0.45762473]
  [0.63080399 0.67570777 0.0513162 ]
  [0.57098733 0.45727588 0.20974409]]

 [[0.36966335 0.56874394 0.64395656]
  [0.32785503 0.44929172 0.22392017]
  [0.14024309 0.69007082 0.70946404]]]


In [ ]:
v = np.random.random((1,2,1))
print(v)

[[[0.70270619]
  [0.66074187]]]


In [ ]:
v = np.random.random((10,10))
#print(v)
v_max,v_min= v.max(), v.min()
print(v_max,v_min)


0.9897264374279745 0.03716944784795151


In [ ]:
v= np.random.random(30)
v_mean= v.mean()
print(v_mean)


0.507414909166525


In [ ]:
v= np.zeros((10,10))
print(v)
v[1:-1,1:-1]= 1
print("********************************")
print(v)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
********************************
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [ ]:
v= np.zeros((10,10))
v[1:-1,1:-1]= 1
print(v)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [ ]:
v= np.ones((5,5))
print(v)
v= np. pad(v,pad_width=1, mode='constant', constant_values=0)
print(v)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [ ]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(0.3 == 3 * 0.1)

nan
False
False
nan
False


In [ ]:
3*0.1


0.30000000000000004

In [ ]:
a = np.nan
b = 5

print(a + b)
print(a * b)
print(b - a)
print(b / a)

nan
nan
nan
nan


In [ ]:

a=np.diag([1,2,3,4,5])
print(a)


[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [ ]:
#create a 5*5 matrix with values 1,2,3,4 just below the diagonal
z=np.diag(1+np.arange(4),k=-2)
print(z)

[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [1 0 0 0 0 0]
 [0 2 0 0 0 0]
 [0 0 3 0 0 0]
 [0 0 0 4 0 0]]
