#*Multiple Regression*

In [ ]:
import pandas as pd
import matplotlib as plt
import numpy as np


In [ ]:
file_path = '/content/homeprices_mlr.csv'
df = pd.read_csv(file_path)
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [ ]:
median = df['bedrooms'].median()

df['bedrooms'] = df['bedrooms'].fillna(median)

df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [ ]:

from sklearn import linear_model

In [ ]:
reg = linear_model.LinearRegression ()

In [ ]:
reg.fit(df.drop('price', axis='columns'), df.price)

LinearRegression()

In [ ]:
reg.coef_

array([  112.06244194, 23388.88007794, -3231.71790863])

In [ ]:
reg.intercept_

221323.00186540396

In [ ]:
reg.predict([[3000, 3, 40]]) # 498408.25158031]

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([498408.25158031])

In [ ]:
y = (3000*112.06244194+3*23388.88007794+40*-3231.71790863)+221323.00186540396
y

498408.251574024

In [ ]:
# trying example on other variables

In [ ]:
from sklearn import linear_model

In [ ]:
reg = linear_model.LinearRegression()

In [ ]:
reg.fit(df.drop ('age', axis ='columns'),df.age)

LinearRegression()

In [ ]:
reg.coef_

array([ 1.09207423e-02, -6.53549070e+00, -4.44080646e-05])

In [ ]:
reg.intercept_


35.20990351192352

In [ ]:
reg.predict([[3000,	4.0	,	565000]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([16.7396112])

In exercise folder (same level as this notebook on github) there is hiring.csv. This file contains hiring statics for a firm such as experience of candidate, his written test score and personal interview score. Based on these 3 factors, HR will decide the salary. Given this data, you need to build a machine learning model for HR department that can help them decide salaries for future candidates. Using this predict salaries for following candidates,

2 yr experience, 9 test score, 6 interview score

12 yr experience, 10 test score, 10 interview score

In [ ]:
path = '/content/hiring.csv'
df =  pd.read_csv(path)
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [ ]:
experience_mapping = {'five': 5, 'two': 2, 'seven': 7, 'three': 3, 'ten': 10, 'eleven': 11}

df['experience'] = df['experience'].map(experience_mapping)
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0         NaN                    8.0                           9      50000
1         NaN                    8.0                           6      45000
2         5.0                    6.0                           7      60000
3         2.0                   10.0                          10      65000
4         7.0                    9.0                           6      70000
5         3.0                    7.0                          10      62000
6        10.0                    NaN                           7      72000
7        11.0                    7.0                           8      80000

In [ ]:
exp_median = df['experience'].median()
tstscor_median = df['test_score(out of 10)'].median()

In [ ]:
df['experience'] = df['experience'].fillna(exp_median)
df['test_score(out of 10)'] = df['test_score(out of 10)'].fillna(tstscor_median)
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0         6.0                    8.0                           9      50000
1         6.0                    8.0                           6      45000
2         5.0                    6.0                           7      60000
3         2.0                   10.0                          10      65000
4         7.0                    9.0                           6      70000
5         3.0                    7.0                          10      62000
6        10.0                    8.0                           7      72000
7        11.0                    7.0                           8      80000

In [ ]:
from sklearn import linear_model

In [ ]:
df = df.rename(columns={'interview_score(out of 10)': 'interview_score'})
df = df.rename(columns={'test_score(out of 10)': 'test_score'})
df = df.rename(columns={'salary($)': 'salary'})
df

experience  test_score  interview_score  salary
0         6.0         8.0                9   50000
1         6.0         8.0                6   45000
2         5.0         6.0                7   60000
3         2.0        10.0               10   65000
4         7.0         9.0                6   70000
5         3.0         7.0               10   62000
6        10.0         8.0                7   72000
7        11.0         7.0                8   80000

In [ ]:
reg = linear_model.LinearRegression()

In [ ]:
reg.fit(df.drop ('salary', axis ='columns'),df.salary)

LinearRegression()

In [ ]:
reg.coef_

array([2813.00813008, 1333.33333333, 2926.82926829])

In [ ]:
reg.intercept_

11869.91869918695

In [ ]:
reg.predict([[6.0	8.0	6]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([1.66211476e+09])